In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [4]:
df = pd.read_csv("DataSetGenOrgMechanism.csv")
df.head()

,reaction_id,substrate_smiles,substrate_class,leaving_group,reagent_smiles,reagent_role,solvent_type,temperature_class,mechanism_class
0,1,CCC(C)(C)I,3°,I,Cl2,radical_source,polar_aprotic,room_temp,other
1,2,CCCCI,1°,I,Br,acid,polar_aprotic,heat,other
2,3,CCC(C)Cl,2°,Cl,Br,acid,polar_aprotic,low,other
3,4,CCCCl,1°,Cl,CO,weak_nucleophile,polar_aprotic,heat,SN2
4,5,CCC(C)Cl,2°,Cl,Br2,radical_source,non_polar,low,other

In [5]:
df.tail()

,reaction_id,substrate_smiles,substrate_class,leaving_group,reagent_smiles,reagent_role,solvent_type,temperature_class,mechanism_class
3995,3996,BrC1CCCCC1,2°,Br,RS-,strong_nucleophile,non_polar,low,other
3996,3997,CCC(C)Cl,2°,Cl,Cl,acid,polar_aprotic,room_temp,other
3997,3998,CC(C)(C)Cl,3°,Cl,Br,acid,polar_aprotic,room_temp,other
3998,3999,CCBr,1°,Br,RS-,strong_nucleophile,polar_aprotic,low,SN2
3999,4000,CC(C)(C)Br,3°,Br,CN-,strong_nucleophile,non_polar,low,other